name: Theme Check

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  theme-check:
    runs-on: ubuntu-latest
    steps:
 - uses: actions/checkout@v4
 - name: Run Shopify Theme Check
        uses: shopify/theme-check-action@v3
